root="/home/vivekrai/analyses/2020-01_vanderbilt_rna/"
BASE_DIR=__dir__
TAG=File.basename(BASE_DIR)

ANNOT_LINK_DIR="/home/vivekrai/analyses/2020-01_vanderbilt_rna/control/module-linked-peaks/work/2021-06-09"

# WGCNA_CUTOFFS = ["0.15", "0.2", "0.25", "0.3"]
WGCNA_CUTOFFS = ["0.2"]

PEAKS=[
  # "hg19.tss.5u1d_ext",
  # "hg19.tss.1kb_ext",
  # "hg19.tss.5kb_ext",
  "hg19.tss.10kb_ext"
]

task :log_dir do
  mkdir_p(["logs", "work/logs"])
end

desc "Prepare BED files which are used with Cicero results"
task :extend_tss do
  SCRIPT = "#{root}/bin/gencodeGTFtoTSS.py"

  puts <<~EOS
    #{SCRIPT} #{root}/data/gtf/gencode.v19.annotation.gtf.gz -l 1000 -r 1000 | \
      grep -v 'chrM' | grep -v 'chrY' > data/hg19.tss.1kb_ext.bed

    #{SCRIPT} #{root}/data/gtf/gencode.v19.annotation.gtf.gz -l 5000 -r 5000 | \
      grep -v 'chrM' | grep  -v 'chrY' > data/hg19.tss.5kb_ext.bed

    #{SCRIPT} #{root}/data/gtf/gencode.v19.annotation.gtf.gz -l 10000 -r 10000 | \
      grep -v 'chrM' | grep -v 'chrY' > data/hg19.tss.10kb_ext.bed

    #{SCRIPT} #{root}/data/gtf/gencode.v19.annotation.gtf.gz -l 5000 -r 1000 | \
      grep -v 'chrM' | grep -v 'chrY' > data/hg19.tss.5u1d_ext.bed
  EOS
end


namespace :module_linked_peaks do
  desc "(Dry-run) Get Cicero linked peaks"
  task :dry_run do
    sh "snakemake -npr --snakefile cicero_linked_peaks.smk"
  end

  desc "Get Cicero linked peaks"
  task :run do
    sh "snakemake --snakefile cicero_linked_peaks.smk"
  end
end


namespace :trait_enrichment do
  desc "(Dry-run) Run GWAS trait enrichment on module-linked peaks"
  task :dry_run do
    sh "snakemake -npr --configfile gwas_config.yaml --snakefile gwas.smk"
  end

  desc "Run GWAS trait enrichment on module-linked peaks"
  task :run do
    sh <<-CMD
      snakemake --cluster-config cluster.yaml --keep-going --snakefile gwas.smk \
        --cluster "sbatch --time {cluster.time} --mem {cluster.mem} --cpus-per-task {cluster.cpus} --job-name {cluster.jobname} -o {cluster.output} -e {cluster.error}  --parsable" \
        -j 10000 -p --latency-wait 4 --configfile gwas_config.yaml&
    CMD
  end

end
